### ISSUE TITLE
Postprocessing

### ISSUE THREAD

**Issue by dmbee** [dmbee/seglearn#16]
New feature: ReconstructTs

Should go in new postprocessing module and reconstruct time series target labels from predictions on segments and mapped to the original data samples. 

This could be implemented using interpolation (nearest neighbor) for categorical targets and anything else for continuous targets. 

I don't think this can be integrated in the current pipeline atm. Another option would be to design another pipeline class that has this implemented as its last step.

**Comment by MisterVulcan** [comment]
IMHO [Pipegraph](https://github.com/mcasl/PipeGraph) might do what you want, basically DAGs for sklearn class objects (including nested pipelines).

**Comment by dmbee** [comment]
Does pipegraph support changing the number of samples? Last I checked it didn't.

**Comment by MisterVulcan** [comment]
I do not know; was thinking in terms of using pipelines as nodes in a graph - it sounds like you already looked into it.
