### ISSUE TITLE
Future warning for transform

### ISSUE THREAD

**Issue by SergioEanX** [dmbee/seglearn#33]
Running your example code "Continuous Target and Time Series Regression" I get many future warnings related to "transform.py" as reported below:
"FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future."

**Comment by dmbee** [comment]
Thanks Sergio - which version of seglearn are you using? This issue should be fixed in the working version 1.0.7 which is on github. 

We haven't updated pypi with a new release for 1.0.7 yet, but this should be coming soon.

**Comment by SergioEanX** [comment]
Currently 1.0.6. 
I can confirm that after upgrading to version 1.0.7 by "pip install -U git+https://github.com/dmbee/seglearn.git" the reported issue has been resolved.
Thanks.

**Comment by dmbee** [comment]
Great thanks.
