### ISSUE TITLE
Can I get the full watch dataset?

### ISSUE THREAD

**Issue by ChangWeiTan** [dmbee/seglearn#42]
Hi, I am working on a similar project on segmenting time series. I am looking for more data to test my models. Your paper https://iopscience.iop.org/article/10.1088/1361-6579/aacfd9/pdf, mentioned that there are 280 time series but there are only 140 series in `watch_dataset.npy`. Would it be possible for me to get a hold of all 280 time series? Thank you

**Comment by dmbee** [comment]
I tried to upload it to the UCI repository, but it seems to take a while for them to process new submissions.

For the time being, you can get the full data set here: 

https://github.com/dmbee/SPAR-dataset

Good luck with your project.

**Comment by ChangWeiTan** [comment]
ok thanks!
