### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by aressler38** [dmbee/seglearn#51]
Hello!

I was reading the user guide, and I think there is a typo in the 1st paragraph of the [time series section](https://dmbee.github.io/seglearn/user_guide.html#time-series-data).

![image](https://user-images.githubusercontent.com/2053500/97742503-bf42d700-1aba-11eb-9e79-272151a10db8.png)

I believe you meant to have <y_i,1, y_i,2, ... y_i,t> instead as you do below. 
![image](https://user-images.githubusercontent.com/2053500/97742639-ec8f8500-1aba-11eb-83d1-74e5c581d9b3.png)

Since you describe **y**_i as being a univariate sequence, I am having trouble seeing how the vector of **x** vectors fits the description, so I _think_ you may have meant to use little-y (non-bold / non-vector *y*) notation in that sentence. Or, perhaps does this mean that **y**_i is the target vector for the corresponding samples < **x**_i,1, ... **x**_i,t > meaning that **y**_i corresponds to the **X**_i sample but is not _composed_ of them. I think the phrasing and use of the word "with" makes it a little confusing if this is the case.

**Comment by dmbee** [comment]
Thanks for your comment. **y_i** is defined <y_i,1, y_i,2, ... y_i,t>

I will revise the documentation accordingly.
