### ISSUE TITLE
will it work for multivariate time series prediction   both regression and classification

### ISSUE THREAD

**Issue by Sandy4321** [dmbee/seglearn#53]
great code thanks
may you clarify : 
will it work for multivariate time series prediction   both regression and classification 
1 
  where all values are continues values 
2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

    color        weight     gender  height  age  
1    black       56              m          160    34
2    white       77              f            170    54
3    yellow      87             m          167     43
4    white       55             m            198    72
5   white       88              f            176     32

**Comment by dmbee** [comment]
will it work for multivariate time series prediction both regression and classification: yes
where all values are continues values: yes
where values are mixture of continues and categorical values: yes

For the last one - you'll need to encode the categorical variables as a number (eg m = 0.0, f = 1.0). Note you can use different features (if you're using engineered feature approach) for different variables with FeatureRepMix, so you can also treat these variables differently that way if you wish.

**Comment by Sandy4321** [comment]
great
do you have code example for 
"where values are mixture of continues and categorical values: yes"

**Comment by dmbee** [comment]
see the examples in the docs eg
https://dmbee.github.io/seglearn/auto_examples/plot_feature_rep.html#sphx-glr-auto-examples-plot-feature-rep-py
