### ISSUE TITLE
question on ts_data

### ISSUE THREAD

**Issue by BrannonKing** [dmbee/seglearn#55]
I have a simple 2D array of data that has samples in the first dimension (rows) and sensors in the 2nd. I understand this is called the "wide" format. It's fairly large: 2 million-ish samples from 100+ sensors. It's in order but there is no date/time column. I have a separate set of labels that contains the same number of samples. I don't understand how to convert this into the required format; I get the error "object has no attribute 'ts_data'". What value is supposed to go in the to-be-created ts_data column?

**Comment by dmbee** [comment]
The dataset format is a list or object-array of time series. If you have just one time series in your dataset you need to put a [ ] around it when passing it to the segmenter or pipeline objects. This requirement is explained in the user guide

**Comment by dmbee** [comment]
https://dmbee.github.io/seglearn/user_guide.html
