### ISSUE TITLE
Pype and Pipeline version incompatible 

### ISSUE THREAD

**Issue by MyRespect** [dmbee/seglearn#59]
Pype version: 1.2.2
Sklearn version: 1.0.1
Python version: 3.8.10

Problem: __init__() takes 2 positional arguments but 3 were given

Solution: change to super(Pype, self).__init__(steps, memory=memory) in seglearn/pipe.py

**Comment by dmbee** [comment]
Thanks for this. I haven't tested for compatibility with sklearn 1.0.1 but will do so and post the fix.
